engines:
  bundler-audit:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
  eslint:
    enabled: true
  fixme:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
  - Gemfile.lock
  - "**.css"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths:
- "spec"
- "coverage"
- "public/javascripts/codemirror-4.8"
- "public/stylesheets/codemirror-4.8"
- "public/stylesheets/bootstrap.min.css"
- "public/stylesheets/bootswatch.min.css"
